FROM eclipse-temurin:8-jre

WORKDIR /app

ADD https://raw.githubusercontent.com/SuvarnaNarayanappa/SuvarnaNarayanappa_B13_e2e_Project_CK/candidate/suvarna/target/devops-demo-0.3.0.jar app.jar

EXPOSE 8081

CMD ["java","-jar","app.jar"]
