pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'terraform-jenkins-integration',
                    url: 'git@github.com:adikarthik/B13.git'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('Terraform/Deepa/Terraform/Terraform-Jenkins') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('Terraform/Deepa/Terraform/Terraform-Jenkins') {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('Terraform/Deepa/Terraform/Terraform-Jenkins') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('Terraform/Deepa/Terraform/Terraform-Jenkins') {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
