---
- name: install tomcat
  hosts: develop
  become: yes
  tasks:
    - name: install java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: create directory for tomcat
      file:
        path: /opt/tomcat
        state: directory

    - name: download tomcat
      command: wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.58/bin/apache-tomcat-9.0.58.tar.gz -O /tmp/apache-tomcat-9.0.58.tar.gz

    - name: extract tomcat
      unarchive:
        src: /tmp/apache-tomcat-9.0.58.tar.gz
        dest: /opt/tomcat
        remote_src: yes

    - name: set permissions for tomcat
      file:
        path: /opt/tomcat/apache-tomcat-9.0.58
        mode: "0755"
        recurse: yes

    - name: copy WAR file
      copy:
        src: /home/raghavendra/Desktop/Amazon/Amazon/Amazon-Web/target/Amazon.war
        dest: /opt/tomcat/apache-tomcat-9.0.58/webapps/Amazon.war

    - name: start tomcat
      command: /opt/tomcat/apache-tomcat-9.0.58/bin/startup.sh