 ---
- name: install tomcat
  hosts: develop
  become: yes
  vars_files:
   - /home/raghavendra/Desktop/playbooks/var.yml
  tasks:
    - name: install java
      apt:
        name: "{{java_version}}"
        state: present
        update_cache: yes

    - name: create directory for tomcat
      file:
        path: /opt/tomcat
        state: directory

    - name: download tomcat
      command: wget "{{tomcat_url}}" -O /tmp/apache-tomcat-9.0.58.tar.gz

    - name: extract tomcat
      unarchive:
        src: /tmp/apache-tomcat-9.0.58.tar.gz
        dest: /opt/tomcat
        remote_src: yes

    - name: set permissions for tomcat
      file:
        path: /opt/tomcat/apache-tomcat-9.0.58
        mode: "0755"
        recurse: yes

    - name: copy WAR file
      copy:
        src: "{{war_file}}"
        dest: /opt/tomcat/apache-tomcat-9.0.58/webapps/Amazon.war
        owner: root
        group: root
        mode: "0644"

    - name: start tomcat
      command: /opt/tomcat/apache-tomcat-9.0.58/bin/startup.sh