---
- name: Handler demo working version
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Copy WAR file
      copy:
        src: files/sample.war
        dest: /tmp/sample.war
      notify: restart tomcat

  handlers:

    - name: restart tomcat
      debug:
        msg: "Tomcat restart simulated successfully"
