---
- name: Install Java Based on OS
  hosts: webservers
  become: yes

  vars:
    java_version: openjdk-17-jdk

  tasks:

    - name: Install Java on Ubuntu
      apt:
        name: "{{ java_version }}"
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      tags:
        - installJava
