---
- name: Deploy Amazon WAR
  hosts: slave
  become: yes

  tasks:

    - name: Copy amazon.war to Tomcat
      copy:
        src: /home/azureuser/amazon.war
        dest: /var/lib/tomcat10/webapps/amazon.war
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: tomcat10
        state: restarted
