- name: Deploy Tomcat and Amazon Application
  hosts: testservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Create Tomcat user
      user:
        name: tomcat
        shell: /bin/bash
        create_home: yes

    - name: Download Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.108/bin/apache-tomcat-9.0.108.tar.gz
        dest: /tmp/tomcat.tar.gz

    - name: Create Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        owner: tomcat
        group: tomcat

    - name: Copy Amazon WAR file
      copy:
        src: /home/azureuser/Amazon.war
        dest: /opt/tomcat/apache-tomcat-9.0.108/webapps/
        owner: tomcat
        group: tomcat

    - name: Start Tomcat
      shell: nohup /opt/tomcat/apache-tomcat-9.0.108/bin/startup.sh &
